app/src/Entity/Form.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\FormRepository")
 */
class Form
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $nombre;

    /**
     * @ORM\Column(type="string", length=150)
     */
    private $mail;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $ciudad;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNombre(): ?string
    {
        return $this->nombre;
    }

    public function setNombre(string $nombre): self
    {
        $this->nombre = $nombre;

        return $this;
    }

    public function getMail(): ?string
    {
        return $this->mail;
    }

    public function setMail(string $mail): self
    {
        $this->mail = $mail;

        return $this;
    }

    public function getCiudad(): ?string
    {
        return $this->ciudad;
    }

    public function setCiudad(string $ciudad): self
    {
        $this->ciudad = $ciudad;

        return $this;
    }
}

app/src/Entity/Opiniones.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\OpinionesRepository")
 */
class Opiniones
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=200)
     */
    private $Nombre;

    /**
     * @ORM\Column(type="string", length=200)
     */
    private $Localización;

    /**
     * @ORM\Column(type="text")
     */
    private $Comentario;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNombre(): ?string
    {
        return $this->Nombre;
    }

    public function setNombre(string $Nombre): self
    {
        $this->Nombre = $Nombre;

        return $this;
    }

    public function getLocalización(): ?string
    {
        return $this->Localización;
    }

    public function setLocalización(string $Localización): self
    {
        $this->Localización = $Localización;

        return $this;
    }

    public function getComentario(): ?string
    {
        return $this->Comentario;
    }

    public function setComentario(string $Comentario): self
    {
        $this->Comentario = $Comentario;

        return $this;
    }
}

app/src/Controller/MaleteoController.php
<?php

namespace App\Controller;

use App\Entity\Opiniones;
use App\Entity\Form;
use App\FormularioApp\FormularioCommentsType;
use App\FormularioApp\UsuariosDemo;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class MaleteoController extends AbstractController
    
{

    /**
     * @Route("/admin", name="listar_usuarios")
     */
    public function listarUsuarios(EntityManagerInterface $em)
    {
        $repositorio = $em->getRepository(Form::class);
        $usuarios= $repositorio->findAll();

        return $this->render(
            'admin.html.twig',
            [
                'usuarios' => $usuarios
            ]

        );

    }

    /**
     * @Route("/", name="homepage")
     */
    public function nuevoUsuario(Request $request, EntityManagerInterface $em)
    {
        $form = $this->createForm(UsuariosDemo::class);
        $form->handleRequest($request);
        $repositorio = $em->getRepository(Opiniones::class);

        $opiniones = $repositorio->findAll();

        if ($form->isSubmitted() && $form->isValid()) {
            $usuarios = $form->getData();
            $em->persist($usuarios);
            $em->flush();

            return $this->redirectToRoute('registro_confirmado');

        }

        return $this->render(
            'maleteoIndex.html.twig',
            [
                'formulario' => $form->createView(),

                'comments' => $opiniones
            ]
        );
    }

    /**
     * @Route("/admin", methods={"POST"}, name="registro_confirmado")
     */
    public function registroConfirmado(EntityManagerInterface $em)
    {
        $repositorio = $em->getRepository(Opiniones::class);
        $opiniones = $repositorio->findAll()();

        return $this->render(
            'registroConfirmado.html.twig',
            [
                'opiniones' => $opiniones
             ]

        );
    }

    /**
     * @Route("/comentarios", name="comentarios")
     */
    public function comentarios(Request $request, EntityManagerInterface $em){

       $comentarios = $this->createForm(FormularioCommentsType::class);

       $comentarios->handleRequest($request);


       if ($comentarios->isSubmitted() && $comentarios->getValid()) {
           $em->persist($comentarios);
           $em->flush();

           return $this->redirectToRoute('homepage');
       }

       return $this->render(
           'comentarios.html.twig',
           [
               'comentarios' => $comentarios->createView(),
           ]
       );
   }
}    

app/templates/admin.html.twig
{% extends 'base.html.twig' %} 
{% block body %}

<table class="table">
<thead class="thead-dark">
    <tr>
        <th scope="col">Nombre</th>
        <th scope="col">Mail</th>
        <th scope="col">Ciudad</th>
    </tr>
</thead>
{% for usuarios in usuarios %}
<tbody>
    <tr>
        <td>{{usuarios.nombre}}</td>
        <td>{{usuarios.email}}</td>
        <td>{{usuarios.ciudad}}</td>
    </tr>
</tbody>
{% endfor %}
</table>



{% endblock %}

app/templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        {% block stylesheets %}{% endblock %}
    </head>
    <body>
        {% block body %}
        {{name}}
        {% endblock %}
        {% block javascripts %}{% endblock %}
    </body>
</html>

app/templates/comentarios.html.twig
{% extends 'base.html.twig'%}

{% block body %}
    <div class="logo">
        <img src="{{ ('Images/logo.svg') }}">
        
    </div>
    <table class="table">
        <thead class="thead-dark">
            <tr>
                <th scope="col">Nombre</th>
                <th scope="col">Localizacion</th>
                <th scope="col">Comentario</th>
                <th scope="col">Guardar</th>
            </tr>
        </thead>
        {{ form_start(comentarios)}}

        <tbody>
            <tr>

                <td>{{form_widget(comentarios.nombre)}}</td>
                <td>{{form_widget(comentarios.localizacion)}}</td>
                <td>{{form_widget(comentarios.comentario)}}</td>
                <td><input type="submit" value="Guardar"></td>
            </tr>
        </tbody>

        {{form_end(comentarios)}}
    </table>


{% endblock %}

app/templates/registroConfirmado.html.twig
{% extends 'maleteoIndex.html.twig'%}


{% block formulario %}
    
    <div id="msg" class="mensaje-alert textLarge">
        <h4>¡Gracias!</h4>
        <p>Tu formulario ha sido enviado correctamente</p>
    </div>


{% endblock %}